### ISSUE TITLE
Waveform Resource Demo

### ISSUE THREAD

**Issue by mmoorewright** [adjacentlink/emane#125]
I'm new to EMANE and I'm in the process of trying to build the configuration for the Waveform Resoursce Demo. However, I am running into an issue when I try to using the "make" command as the instructions state. Below is the error messages I'm receiving. Any help would be greatly appreciated. 

letce2 \
	lxc \
	build \
	experiment.cfg
Traceback (most recent call last):
  File "/usr/bin/letce2", line 5, in <module>
    pkg_resources.run_script('letce2==0.2.4', 'letce2')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/letce2-0.2.4-py2.7.egg/EGG-INFO/scripts/letce2", line 105, in <module>
    
ImportError: No module named lxc
make: *** [all] Error 1

**Comment by sgalgano** [comment]
This is not an emane question.
