### ISSUE TITLE
EMANE and CORE : node device failed to exist 

### ISSUE THREAD

**Issue by vandit86** [adjacentlink/emane#208]
**Describe the bug**
I think it is a CORE error, but maybe someone could help me on this: 
Running any example with **emane** wlan network is leading to _"Exception calling application: node device failed to exist"_
This type of error appears running in CORE locally **or** in docker.

![delete](https://user-images.githubusercontent.com/16361531/156019672-47c66b57-5593-4293-8f4b-8d273f5aa25d.png)

```
2022-02-28 16:19:00,614 - ERROR - app:show_grpc_exception - app grpc exception
Traceback (most recent call last):
  File "/home/vad/core/daemon/core/gui/coreclient.py", line 425, in start_session
    result, exceptions = self.client.start_session(self.session, definition)
  File "/home/vad/core/daemon/core/api/grpc/client.py", line 239, in start_session
    response = self.stub.StartSession(request)
  File "/home/vad/.cache/pypoetry/virtualenvs/core-mm-NMljy-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/vad/.cache/pypoetry/virtualenvs/core-mm-NMljy-py3.8/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: node device failed to exist"
	debug_error_string = "{"created":"@1646065140.613823085","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Exception calling application: node device failed to exist","grpc_status":2}"
```

I will appreciate any suggestion.. 

**Desktop:**
 - OS: Mint 20.04
 - CORE Version 8.1.0
 - EMANE Version 1.3.3

**Comment by bharnden** [comment]
It appears as though you are not running the `core-daemon` for the GUI to connect.

I would not post issues to adjacentlink, unless it is an actual issue identified in EMANE.
